-- Creación de las tablas de manera estructurada

CREATE DATABASE IF NOT exists AdmBD;

USE AdmBD;

CREATE TABLE DEPARTAMENTOS (
    ID_DEPARTAMENTO INT(10) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(100)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT(10) AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(100),
    CARGO VARCHAR(100),
    SALARIO DOUBLE,
    DEPARTAMENTO INT NOT NULL,
    FECHA_INGRESO DATE,
    FECHA_RETIRO DATE null,
    foreign key(DEPARTAMENTO) references departamentos(ID_DEPARTAMENTO)
);

CREATE TABLE SALARIOS_HISTORICOS (
    ID INT(10) AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT(10),
    FECHA_CAMBIO DATE,
    NUEVO_SALARIO DOUBLE,
    foreign key(ID_EMPLEADO) references EMPLEADOS(ID_EMPLEADO) on delete cascade
);

CREATE TABLE PERMISOS_VACACIONES (
    ID_PERMISO INT(10) AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT(10),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    MOTIVO VARCHAR(100),
    foreign key(ID_EMPLEADO) references EMPLEADOS(ID_EMPLEADO) on delete cascade
);

CREATE TABLE EVALUACIONES_DESEMPENO (
    ID_EVALUACION INT(10) AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT(10),
    PUNTUACION DOUBLE,
    OBSERVACIONES VARCHAR(100),
    FECHA_EVALUACION DATE,
    foreign key(ID_EMPLEADO) references EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE CONCEPTOS (
    ID INT(10) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    SIGNO VARCHAR(100)
);

CREATE TABLE PERIODOS (
    ID INT(10) auto_increment primary key,
    DESCRIPCION VARCHAR(100),
    FECHA_INICIAL DATE,
    FECHA_FINAL DATE,
    ESTADO VARCHAR(100)
);

CREATE TABLE CONCEPTOS_SALARIO (
	ID_CONCEPTOS INT(10) auto_increment primary Key,
    ID_PERIODO INT(10),
    ID_CONCEPTO INT(10),
    ID_EMPLEADO INT(10),
    MONTO DOUBLE,
    FECHA_LIQUIDACION DATE,
    foreign key(ID_PERIODO) references PERIODOS(ID),
    foreign key(ID_CONCEPTO) references CONCEPTOS(ID),
    foreign key(ID_EMPLEADO) references EMPLEADOS(ID_EMPLEADO) on delete cascade
);

CREATE TABLE EMPLEADOS_VACACIONES (
    ID_VACACION INT(10) auto_increment primary key,
    ID_EMPLEADO INT(10),
    PERIODO_ANUAL DATE,
    SALDO_DIAS INT(10),
    FECHA_ACTUALIZACION DATE,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO) on delete cascade
)
