-- INSERT en la tabla DEPARTAMENTOS
INSERT ALL
    INTO DEPARTAMENTOS (NOMBRE_DEPARTAMENTO) VALUES ('Recursos Humanos')
    INTO DEPARTAMENTOS (NOMBRE_DEPARTAMENTO) VALUES ('Tecnología')
    INTO DEPARTAMENTOS (NOMBRE_DEPARTAMENTO) VALUES ('Marketing')
    INTO DEPARTAMENTOS (NOMBRE_DEPARTAMENTO) VALUES ('Ventas')
    INTO DEPARTAMENTOS (NOMBRE_DEPARTAMENTO) VALUES ('Finanzas')
SELECT 1 FROM DUAL;

-- INSERT en la tabla EMPLEADOS
INSERT ALL
    INTO EMPLEADOS (NOMBRES, CARGO, SALARIO, DEPARTAMENTO, FECHA_INGRESO, FECHA_RETIRO) 
    VALUES ('Juan Pérez', 'Gerente', 3500.50, 1, TO_DATE('2020-01-15', 'YYYY-MM-DD'), NULL)
    INTO EMPLEADOS (NOMBRES, CARGO, SALARIO, DEPARTAMENTO, FECHA_INGRESO, FECHA_RETIRO) 
    VALUES ('Ana Gómez', 'Desarrolladora', 2500.00, 2, TO_DATE('2021-03-10', 'YYYY-MM-DD'), NULL)
    INTO EMPLEADOS (NOMBRES, CARGO, SALARIO, DEPARTAMENTO, FECHA_INGRESO, FECHA_RETIRO) 
    VALUES ('Luis Torres', 'Vendedor', 1500.00, 4, TO_DATE('2019-08-01', 'YYYY-MM-DD'), TO_DATE('2023-02-10', 'YYYY-MM-DD'))
    INTO EMPLEADOS (NOMBRES, CARGO, SALARIO, DEPARTAMENTO, FECHA_INGRESO, FECHA_RETIRO) 
    VALUES ('María López', 'Analista Financiera', 2800.00, 5, TO_DATE('2018-06-20', 'YYYY-MM-DD'), NULL)
    INTO EMPLEADOS (NOMBRES, CARGO, SALARIO, DEPARTAMENTO, FECHA_INGRESO, FECHA_RETIRO) 
    VALUES ('Pedro Sánchez', 'Especialista en Marketing', 2200.00, 3, TO_DATE('2020-11-05', 'YYYY-MM-DD'), NULL)
SELECT 1 FROM DUAL;

-- INSERT en la tabla SALARIOS_HISTORICOS
INSERT ALL
    INTO SALARIOS_HISTORICOS (ID_EMPLEADO, FECHA_CAMBIO, NUEVO_SALARIO) 
    VALUES (6, TO_DATE('2021-01-01', 'YYYY-MM-DD'), 3600.00)
    INTO SALARIOS_HISTORICOS (ID_EMPLEADO, FECHA_CAMBIO, NUEVO_SALARIO) 
    VALUES (7, TO_DATE('2022-04-15', 'YYYY-MM-DD'), 2600.00)
    INTO SALARIOS_HISTORICOS (ID_EMPLEADO, FECHA_CAMBIO, NUEVO_SALARIO) 
    VALUES (8, TO_DATE('2020-12-01', 'YYYY-MM-DD'), 1600.00)
    INTO SALARIOS_HISTORICOS (ID_EMPLEADO, FECHA_CAMBIO, NUEVO_SALARIO) 
    VALUES (9, TO_DATE('2019-07-01', 'YYYY-MM-DD'), 2900.00)
    INTO SALARIOS_HISTORICOS (ID_EMPLEADO, FECHA_CAMBIO, NUEVO_SALARIO) 
    VALUES (10, TO_DATE('2021-11-01', 'YYYY-MM-DD'), 2300.00)
SELECT 1 FROM DUAL;

-- INSERT en la tabla PERMISOS_VACACIONES
INSERT ALL
    INTO PERMISOS_VACACIONES (ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, MOTIVO) 
    VALUES (6, TO_DATE('2022-12-01', 'YYYY-MM-DD'), TO_DATE('2022-12-15', 'YYYY-MM-DD'), 'Vacaciones anuales')
    INTO PERMISOS_VACACIONES (ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, MOTIVO) 
    VALUES (7, TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2023-06-07', 'YYYY-MM-DD'), 'Asuntos personales')
    INTO PERMISOS_VACACIONES (ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, MOTIVO) 
    VALUES (8, TO_DATE('2021-05-15', 'YYYY-MM-DD'), TO_DATE('2021-05-30', 'YYYY-MM-DD'), 'Licencia médica')
    INTO PERMISOS_VACACIONES (ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, MOTIVO) 
    VALUES (9, TO_DATE('2020-09-20', 'YYYY-MM-DD'), TO_DATE('2020-09-25', 'YYYY-MM-DD'), 'Viaje familiar')
    INTO PERMISOS_VACACIONES (ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, MOTIVO) 
    VALUES (10, TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-02-10', 'YYYY-MM-DD'), 'Vacaciones anuales')
SELECT 1 FROM DUAL;

-- INSERT en la tabla EVALUACIONES_DESEMPENO
INSERT ALL
    INTO EVALUACIONES_DESEMPENO (ID_EMPLEADO, PUNTUACION, OBSERVACIONES, FECHA_EVALUACION) 
    VALUES (6, 4.5, 'Excelente desempeño', TO_DATE('2022-01-15', 'YYYY-MM-DD'))
    INTO EVALUACIONES_DESEMPENO (ID_EMPLEADO, PUNTUACION, OBSERVACIONES, FECHA_EVALUACION) 
    VALUES (7, 4.0, 'Buen desempeño', TO_DATE('2023-03-10', 'YYYY-MM-DD'))
    INTO EVALUACIONES_DESEMPENO (ID_EMPLEADO, PUNTUACION, OBSERVACIONES, FECHA_EVALUACION) 
    VALUES (8, 3.0, 'Mejorable', TO_DATE('2020-08-01', 'YYYY-MM-DD'))
    INTO EVALUACIONES_DESEMPENO (ID_EMPLEADO, PUNTUACION, OBSERVACIONES, FECHA_EVALUACION) 
    VALUES (9, 4.8, 'Desempeño destacado', TO_DATE('2021-06-20', 'YYYY-MM-DD'))
    INTO EVALUACIONES_DESEMPENO (ID_EMPLEADO, PUNTUACION, OBSERVACIONES, FECHA_EVALUACION) 
    VALUES (10, 3.5, 'Satisfactorio', TO_DATE('2022-11-05', 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

-- INSERT en la tabla CONCEPTOS
INSERT ALL
    INTO CONCEPTOS (NOMBRE, SIGNO) 
    VALUES ('Bono', '+')
    INTO CONCEPTOS (NOMBRE, SIGNO) 
    VALUES ('Descuento', '-')
    INTO CONCEPTOS (NOMBRE, SIGNO) 
    VALUES ('Comisión', '+')
    INTO CONCEPTOS (NOMBRE, SIGNO) 
    VALUES ('Ajuste Salarial', '+')
    INTO CONCEPTOS (NOMBRE, SIGNO) 
    VALUES ('Impuesto', '-')
SELECT 1 FROM DUAL;

-- INSERT en la tabla PERIODOS
INSERT ALL
    INTO PERIODOS (DESCRIPCION, FECHA_INICIAL, FECHA_FINAL, ESTADO) 
    VALUES ('Primer trimestre 2022', TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2022-03-31', 'YYYY-MM-DD'), 'Cerrado')
    INTO PERIODOS (DESCRIPCION, FECHA_INICIAL, FECHA_FINAL, ESTADO) 
    VALUES ('Segundo trimestre 2022', TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-06-30', 'YYYY-MM-DD'), 'Cerrado')
    INTO PERIODOS (DESCRIPCION, FECHA_INICIAL, FECHA_FINAL, ESTADO) 
    VALUES ('Tercer trimestre 2022', TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2022-09-30', 'YYYY-MM-DD'), 'Cerrado')
    INTO PERIODOS (DESCRIPCION, FECHA_INICIAL, FECHA_FINAL, ESTADO) 
    VALUES ('Cuarto trimestre 2022', TO_DATE('2022-10-01', 'YYYY-MM-DD'), TO_DATE('2022-12-31', 'YYYY-MM-DD'), 'Cerrado')
    INTO PERIODOS (DESCRIPCION, FECHA_INICIAL, FECHA_FINAL, ESTADO) 
    VALUES ('Primer trimestre 2023', TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2023-03-31', 'YYYY-MM-DD'), 'Abierto')
SELECT 1 FROM DUAL;

-- INSERT en la tabla CONCEPTOS_SALARIO
INSERT ALL
    INTO CONCEPTOS_SALARIO (ID_PERIODO, ID_CONCEPTO, ID_EMPLEADO, MONTO, FECHA_LIQUIDACION) 
    VALUES (31, 26, 6, 500.00, TO_DATE('2022-01-31', 'YYYY-MM-DD'))
    INTO CONCEPTOS_SALARIO (ID_PERIODO, ID_CONCEPTO, ID_EMPLEADO, MONTO, FECHA_LIQUIDACION) 
    VALUES (32, 27, 7, 200.00, TO_DATE('2022-06-30', 'YYYY-MM-DD'))
    INTO CONCEPTOS_SALARIO (ID_PERIODO, ID_CONCEPTO, ID_EMPLEADO, MONTO, FECHA_LIQUIDACION) 
    VALUES (33, 28, 8, 150.00, TO_DATE('2022-09-30', 'YYYY-MM-DD'))
    INTO CONCEPTOS_SALARIO (ID_PERIODO, ID_CONCEPTO, ID_EMPLEADO, MONTO, FECHA_LIQUIDACION) 
    VALUES (34, 29, 9, 300.00, TO_DATE('2022-12-31', 'YYYY-MM-DD'))
    INTO CONCEPTOS_SALARIO (ID_PERIODO, ID_CONCEPTO, ID_EMPLEADO, MONTO, FECHA_LIQUIDACION) 
    VALUES (35, 30, 10, 100.00, TO_DATE('2023-03-31', 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

-- INSERT en la tabla EMPLEADOS_VACACIONES
INSERT ALL
    INTO EMPLEADOS_VACACIONES (ID_EMPLEADO, PERIODO_ANUAL, SALDO_DIAS, FECHA_ACTUALIZACION) 
    VALUES ((select id_empleado from empleados where Nombres = 'Juan Pérez'), TO_DATE('2022-01-01', 'YYYY-MM-DD'), 15, TO_DATE('2022-12-31', 'YYYY-MM-DD'))
    INTO EMPLEADOS_VACACIONES (ID_EMPLEADO, PERIODO_ANUAL, SALDO_DIAS, FECHA_ACTUALIZACION) 
    VALUES ((select id_empleado from empleados where Nombres = 'Ana Gómez'), TO_DATE('2023-01-01', 'YYYY-MM-DD'), 10, TO_DATE('2023-06-01', 'YYYY-MM-DD'))
    INTO EMPLEADOS_VACACIONES (ID_EMPLEADO, PERIODO_ANUAL, SALDO_DIAS, FECHA_ACTUALIZACION) 
    VALUES ((select id_empleado from empleados where Nombres = 'Luis Torres'), TO_DATE('2021-01-01', 'YYYY-MM-DD'), 20, TO_DATE('2021-05-30', 'YYYY-MM-DD'))
    INTO EMPLEADOS_VACACIONES (ID_EMPLEADO, PERIODO_ANUAL, SALDO_DIAS, FECHA_ACTUALIZACION) 
    VALUES ((select id_empleado from empleados where Nombres = 'María López'), TO_DATE('2020-01-01', 'YYYY-MM-DD'), 5, TO_DATE('2020-09-25', 'YYYY-MM-DD'))
    INTO EMPLEADOS_VACACIONES (ID_EMPLEADO, PERIODO_ANUAL, SALDO_DIAS, FECHA_ACTUALIZACION) 
    VALUES ((select id_empleado from empleados where Nombres = 'Pedro Sánchez'), TO_DATE('2023-01-01', 'YYYY-MM-DD'), 12, TO_DATE('2023-02-10', 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;
